name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Fmt
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy

  build_windows_release:
    needs: [build]

    name: Build windows release

    runs-on: windows-latest

    #strategy:
    #  matrix:
    #    include:
    #      - os: ubuntu-latest
    #        artifact_name: bevy_snake
    #        asset_name: snake-linux-amd64
    #      - os: windows-latest
    #        artifact_name: bevy_snake.exe
    #        asset_name: snake-windows-amd64
    #      #- os: macos-latest
    #      #  artifact_name: bevy_snake
    #      #  asset_name: snake-macos-amd64

    steps:
    # - name: Install deps
    #   run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
    #   if: runner.os == 'linux'
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --locked
  
  release_windows_release:
    needs: [build_windows_release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Copy resources
      run: |
        cp target/release/bevy_snake.exe .
        cp -r bevy-snake/assets/ assets/
    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: bevy_snake.exe assets
        dest: bevy_snake_windows.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bevy_snake_windows.zip
        asset_name: bevy_snake_windows.zip
        tag: ${{ github.ref }}
        overwrite: true
