name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - name: Info
      run: sudo lshw -C display
    - name: Install deps
      run: |
        sudo apt update
        sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libvulkan1 mesa-vulkan-drivers vulkan-utils vulkan-sdk
    - name: Info2
      run: vulkaninfo
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Fmt
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy

  windows_release:
    needs: [build]
    name: Build windows release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --locked
    - name: Copy resources
      run: |
        cp target/release/bevy_snake.exe .
        mkdir assets
        cp -r bevy-snake/assets/ assets/
    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: bevy_snake.exe assets
        dest: bevy_snake_windows.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bevy_snake_windows.zip
        asset_name: bevy_snake_windows.zip
        tag: ${{ github.ref }}
        overwrite: true

  linux_release:
    needs: [build]
    name: Build linux release
    runs-on: ubuntu-20.04

    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libvulkan1 mesa-vulkan-drivers vulkan-utils
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --locked
    - name: Copy resources
      run: |
        cp target/release/bevy_snake .
        mkdir assets
        cp -r bevy-snake/assets/ assets/
    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: bevy_snake assets
        dest: bevy_snake_linux.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bevy_snake_linux.zip
        asset_name: bevy_snake_linux.zip
        tag: ${{ github.ref }}
        overwrite: true

  web_release:
    needs: [build]
    name: Build web release
    runs-on: ubuntu-20.04

    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libvulkan1 mesa-vulkan-drivers vulkan-utils
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build handly-made-snake
      run: |
        cargo install wasm-pack
        wasm-pack build --release handly-made-snake
        cd handly-made-snake/www
        npm ci
        npm run build
    - name: Build bevy-snake
      run: |
        cargo install --locked trunk
        cd bevy-snake
        trunk build --release
    - name: Copy resources
      run: |
        cp -r handly-made-snake/www/dist handly-made-snake-dist
        cp -r bevy-snake/dist bevy-snake-dist
        mv handly-made-snake-dist/index.html handly-made-snake-dist/handly-made-snake.html
        mv bevy-snake-dist/index.html bevy-snake-dist/bevy-snake.html
        echo '<html><a href="./bevy-snake.html">bevy-snake</a><a href="./handly-made-snake.html">handly-made-snake</a></html>' >> bevy-snake-dist/index.html
        mkdir dist
        mv handly-made-snake-dist/* dist
        mv bevy-snake-dist/* dist
    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: dist
        dest: bevy_snake_web.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bevy_snake_web.zip
        asset_name: bevy_snake_web.zip
        tag: ${{ github.ref }}
        overwrite: true
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist